### ISSUE TITLE
How to integrate Modoo with latest HA versions?

### ISSUE THREAD

**Issue by Swiftnesses** [avassem85/HomeAssistantConfiguration#1]
Hi,

I'd love to use your Modoo integration, how can this be done in the latest versions (custom components have changed). I tried changing modoo.py to __init__.py and renaming the fan py to fan.py but have had no luck :(

**Comment by avassem85** [comment]
Creat a folder Moodo in Custom Components:
Rename moodo.py (in home) to init.py and move to Moodo folder
Rename moodo.py (in fan) to fan.py and move to Moodo folder
Create manifest.json with content and put it in Moodo folder
{
    "domain": "moodo",
    "name": "Moodo",
    "documentation": "https://github.com/avassem85/hassio-config",
    "requirements": [
      "pymoodo==0.0.2"
    ],
    "dependencies": [],
    "codeowners": [
      "@avassem85"
    ]
  }

**Comment by Swiftnesses** [comment]
Hello,

I already tried that, but sadly it doesn't work (at least for me!).

The logs show:

```
Error loading custom_components.modoo. Make sure all dependencies are installed
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 346, in _load_file
    module = importlib.import_module(path)
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/config/custom_components/modoo/__init__.py", line 19, in <module>
    from pymoodo import Controller
ModuleNotFoundError: No module named 'pymoodo'
```

**Comment by Swiftnesses** [comment]
Ouch, all because my brain keeps trying to call this thing "Modoo", looks like I had a typo in my folder name!

**Comment by Swiftnesses** [comment]
Sorted - not having much look with it though, do you find the status of the switches updates well?

I'm also struggling to understand the relation between the main fan speed / switch and the capsule fan speed / switch settings :-/

**Comment by Swiftnesses** [comment]
Yes, after playing around with it - it seems my Moodo has a mind of its own via this component. The app works just fine... 

Adjusting individual scents via the component makes other scents randomly decrease / increase (I can't find any logic).

**Comment by Jens-Wymeersch** [comment]
@avassem85 Hi Alex, would it be possible to make an HACS component for the Moodo ?
